blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/CaviraOSS/neuropilot/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/CaviraOSS/neuropilot/wiki
    about: Check out the project documentation
  - name: 🔒 Security Issue
    url: https://github.com/CaviraOSS/neuropilot/security/advisories/new
    about: Report a security vulnerability privately
